Config = {}

Config.Weapons = {
    [`WEAPON_UNARMED`] = {model = `WEAPON_UNARMED`, modifier = 0.7, disableCritical = true},
    [`WEAPON_PISTOL`] = {model = `WEAPON_PISTOL`, modifier = 0.6, disableCritical = true},
    [`WEAPON_PISTOL_MK2`] = {model = `WEAPON_PISTOL_MK2`, modifier = 0.6, disableCritical = true},
    [`WEAPON_COMBATPISTOL`] = {model = `WEAPON_COMBATPISTOL`, modifier = 0.8, disableCritical = true},
    [`WEAPON_PISTOL50`] = {model = `WEAPON_PISTOL50`, modifier = 0.6, disableCritical = true},
    [`WEAPON_SNSPISTOL`] = {model = `WEAPON_SNSPISTOL`, modifier = 0.6, disableCritical = true},
    [`WEAPON_HEAVYPISTOL`] = {model = `WEAPON_HEAVYPISTOL`, modifier = 0.6, disableCritical = true},
    [`WEAPON_VINTAGEPISTOL`] = {model = `WEAPON_VINTAGEPISTOL`, modifier = 0.6, disableCritical = true},
    [`WEAPON_MICROSMG`] = {model = `WEAPON_MICROSMG`, modifier = 0.7, disableCritical = true},
    [`WEAPON_MACHINEPISTOL`] = {model = `WEAPON_MACHINEPISTOL`, modifier = 0.6, disableCritical = true},
    [`WEAPON_SMG`] = {model = `WEAPON_SMG`, modifier = 0.9, disableCritical = true},
    [`WEAPON_SMG_MK2`] = {model = `WEAPON_SMG_MK2`, modifier = 0.6, disableCritical = true},
    [`WEAPON_MINISMG`] = {model = `WEAPON_MINISMG`, modifier = 0.6, disableCritical = true},
    [`WEAPON_APPISTOL`] = {model = `WEAPON_APPISTOL`, modifier = 0.6, disableCritical = true},
    [`WEAPON_SAWNOFFSHOTGUN`] = {model = `WEAPON_SAWNOFFSHOTGUN`, modifier = 0.3, disableCritical = true},
    [`WEAPON_REVOLVER_MK2`] = {model = `WEAPON_REVOLVER_MK2`, modifier = 0.5, disableCritical = true},
    [`WEAPON_REVOLVER`] = {model = `WEAPON_REVOLVER`, modifier = 0.5, disableCritical = true},
    [`WEAPON_CARBINERIFLE_MK2`] = {model = `WEAPON_CARBINERIFLE_MK2`, modifier = 0.75, disableCritical = true},
    [`WEAPON_CARBINERIFLE`] = {model = `WEAPON_CARBINERIFLE`, modifier = 0.6, disableCritical = true},
    [`WEAPON_SPECIALCARBINE`] = {model = `WEAPON_SPECIALCARBINE`, modifier = 0.7, disableCritical = true},
    [`WEAPON_SPECIALCARBINE_MK2`] = {model = `WEAPON_SPECIALCARBINE_MK2`, modifier = 0.75, disableCritical = true},
    [`WEAPON_PUMPSHOTGUN_MK2`] = {model = `WEAPON_PUMPSHOTGUN_MK2`, modifier = 0.5, disableCritical = true},
    [`WEAPON_COMPACTRIFLE`] = {model = `WEAPON_COMPACTRIFLE`, modifier = 0.6, disableCritical = true},
    [`WEAPON_HEAVYSHOTGUN`] = {model = `WEAPON_HEAVYSHOTGUN`, modifier = 0.3, disableCritical = true},
    [`WEAPON_ASSAULTRIFLE`] = {model = `WEAPON_ASSAULTRIFLE`, modifier = 0.6, disableCritical = true},
    [`WEAPON_ASSAULTRIFLE_MK2`] = {model = `WEAPON_ASSAULTRIFLE_MK2`, modifier = 0.6, disableCritical = true},
    [`WEAPON_COMBATPDW`] = {model = `WEAPON_COMBATPDW`, modifier = 0.7, disableCritical = true},
    [`WEAPON_PUMPSHOTGUN`] = {model = `WEAPON_PUMPSHOTGUN`, modifier = 0.5, disableCritical = true},
    [`WEAPON_SMG_MK2`] = {model = `WEAPON_SMG_MK2`, modifier = 0.7, disableCritical = true},
    [`WEAPON_ASSAULTSMG`] = {model = `WEAPON_ASSAULTSMG`, modifier = 0.7, disableCritical = true},
    [`WEAPON_ADVANCEDRIFLE`] = {model = `WEAPON_ADVANCEDRIFLE`, modifier = 0.7, disableCritical = true},
}